[versions]
slf4j = "2.0.17"

[libraries]
# Core
fluava = { module = "dev.goldmensch:fluava", version = "1.2.3" }
jemoji = { module = "net.fellbaum:jemoji", version = "1.7.5"}
jda = { module = "net.dv8tion:JDA", version = "6.3.0" }
guice = { module = "com.google.inject:guice", version = "7.0.0" }
proteus = { module = "io.github.kaktushose:proteus", version = "0.2.3" }

# Utils
asm = { module = "org.ow2.asm:asm", version = "9.9.1" }
classgraph = { module = "io.github.classgraph:classgraph", version = "4.8.184" }
jackson = { module = "tools.jackson.core:jackson-databind", version = "3.0.4" }
javapoet = { module = "com.palantir.javapoet:javapoet", version = "0.10.0" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

# Annotations
jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2" }
jspecify = { module = "org.jspecify:jspecify", version = "1.0.0"}

# Testing
jakarta = { module = "jakarta.inject:jakarta.inject-api", version = "2.0.1" }
junit = { module = "org.junit.jupiter:junit-jupiter", version = "6.0.2" }
mockito-core = { module = "org.mockito:mockito-core", version = "5.21.0" }


[bundles]
slf4j = [
    "slf4j-api",
    "slf4j-simple"
]

[plugins]
aggregate-javadoc = "io.freefair.aggregate-javadoc:8.12.2.1"