name: Documentation

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate Documentation
        run: |
          mvn javadoc:aggregate
      - name: Checkout Docs Branch
        run: |
          git checkout docs
          git pull
      - name: Move Files
        run: |
          rm -rf ./docs
          mv ./target/site/apidocs/ ./docs
          rm -rf ./target
      - name: Modify search.js
        run: echo 'getURLPrefix = function(ui) {return "";};' >> ./docs/search.js
      - name: Commit & Push Changes
        run: |
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git config --global user.name github-actions[bot]
          git add .
          git commit -m "update documentation"
          git push
