name: Wiki build & test

on:
  push:
  pull_request:

jobs:
  build-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup-gradle
      - name: Generate javadocs with Gradle
        run: ./gradlew javadoc
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
      - name: Build Wiki
        id: build
        run: |
          cd wiki
          pip install -r requirements.txt
          
          # replace online javadocs with local ones
          sed -i -e 's#https://kaktushose.github.io/jda-commands/javadocs/JDAC_JAVADOC_VERSION/#../jda-commands/build/docs/javadoc/#g' mkdocs.yml

          # replace all JDAC_JAVADOC_VERSION with actual version
          grep -rl 'https' ./ | xargs sed -i -e 's/JDAC_JAVADOC_VERSION/snapshot/g'
          
          out="$(mkdocs build --verbose 2>&1)" # 2>&1 -> redirect err out to std out
          echo "$out"
          
          {
            echo "out<<EOF"
            echo "$out"
            echo "EOF"
          } >> "$GITHUB_OUTPUT"
      - name: Check for errors
        run: |
          out="
          ${{ steps.build.outputs.out }}
          "
          
          errs=$(echo "$out" | grep -E 'WARNING|ERROR')
          
          if [[ -n "$errs" ]]; then
            echo "Found warnings or errors:"
            printf '%s\n' "$errs"
            exit 1
          fi
